### ISSUE TITLE
Path to Stage 4!

### ISSUE THREAD

**Issue by gibson042** [Agoric/tc39-proposal-immutable-arraybuffer#1]
## Stage 4
* [ ]  committee approval
* [ ]  two implementations
  * [ ]  JavaScriptCore
  * [ ]  SpiderMonkey
  * [ ]  XS
  * [ ]  V8
* [ ]  significant in-the-field experience
* [ ]  ecma262 PR approved
* [ ]  prepare ecma262 PR
* [ ]  merge test262 tests
* [ ]  write test262 tests

## Stage 3
* [ ]  resolve open questions
* [ ]  committee approval
* [ ]  spec editor signoff
* [ ]  spec reviewer signoff
* [ ]  receive implementer feedback

## Stage 2
* [ ]  committee approval
* [ ]  spec reviewers selected
* [x]  spec text written

## Stage 1
* [ ]  committee approval

**Comment by erights** [comment]
@syg @waldemarhorwat @ljharb , with the normative issues resolved aside from the purposely postponed #16 (see checklist above), This seems ready for spec review. I have placed this item on the agenda to go for 2.7, so would like to be as prepared as possible.

For the "spec editor signoff", who are the spec editors?

**Comment by syg** [comment]
You can tag @tc39/ecma262-editors. Currently the editors are myself, @bakkot, and @michaelficarra.

**Comment by erights** [comment]
@syg @waldemarhorwat @bakkot @michaelficarra ping. 

@syg @bakkot please see @gibson042 responses to your stated concerns. What remaining concerns do you have that should block 2.7 until resolved?

@waldemarhorwat @michaelficarra I'd love to see your feedback before asking for stage 2.7.

Thanks!

**Comment by syg** [comment]
Current spec draft editorially and normatively lgtm.

**Comment by waldemarhorwat** [comment]
Looks good to me, with just one comment:

* Why does `sliceToImmutable` diverge from `slice` when *end* < *start*? That seems like needless inconsistency. Having one of these clamp to zero and one throw will confuse users and cause subtle bugs if someone refactors `sliceToImmutable` to `slice`.

**Comment by ljharb** [comment]
(no opinion on the outcome) but wouldn't the exception _prevent_ subtle bugs caused by the clamping, by throwing?

**Comment by waldemarhorwat** [comment]
See my comment above. Hardly anyone will remember which one clamps and which one throws, so folks relying on throwing will be in for a rude surprise.

**Comment by ljharb** [comment]
ahhh gotcha, you mean going "backwards". fair point.

**Comment by gibson042** [comment]
> Why does `sliceToImmutable` diverge from `slice` when _end_ < _start_? That seems like needless inconsistency.

Producing a zero-length immutable buffer from code like `buf.sliceToImmutable(4, 2)` was deemed so useless and undesirable that an exception was warranted even with divergence from `ArrayBuffer.prototype.slice`. But it's true that every method named `slice` performs such clamping, and maybe that counterpoint is heavy enough to justify internal consistency here.

**Comment by erights** [comment]
@waldemarhorwat I think this is explicitly covered by #16 , which is still open. We felt that for the sake of concreteness it was better for the champions to specify according to their preferences at the moment, as long as there is an open issue covering the remaining controversy.

In any case, I agree with @gibson042 here, that we are open to removing this difference with `slice`.

Given that, may we check your 2.7 reviewer checkbox (just in time for my presentation ;) )

**Comment by gibson042** [comment]
> Why does `sliceToImmutable` diverge from `slice` when _end_ < _start_? That seems like needless inconsistency.

#41

**Comment by erights** [comment]
@gibson042 , thanks!

I just approved and merged #41 

@waldemarhorwat , in light of your verbal agreement, I'm clicking your checkbox. If we've misunderstood anything, please uncheck and let us know.

**Comment by anba** [comment]
SpiderMonkey status:
- Initial implementation available in Nightly builds when enabling the `javascript.options.experimental.arraybuffer_immutable` flag. (<https://bugzilla.mozilla.org/show_bug.cgi?id=1966355>)
- Includes structured cloning support per <https://github.com/whatwg/html/pull/11033>.
- Web platforms APIs currently all reject immutable array buffers and views: <https://github.com/whatwg/webidl/issues/1487>.
- No further optimisations implemented which are possible with immutable buffers.

**Comment by styfle** [comment]
Was there a decision on `preserveResizability` vs `mode`?

- https://github.com/tc39/proposal-immutable-arraybuffer/pull/35

The comment says the name is subject to change before acceptance into ECMA-262 (which I think is the same as Stage 4).

**Comment by erights** [comment]
> The comment says the name is subject to change before acceptance into ECMA-262 (which I think is the same as Stage 4).

While I would agree that if it is going to change, then changing before stage 4 would be best. However, technically, if it does not change by then, since it would be purely an editorial PR (no observable difference), it could change anytime after with only a editor-approved PR. @gibson042 @styfle , agreed?

Btw, I also agree that it should change to `mode`.

**Comment by michaelficarra** [comment]
@erights @styfle That's something that we typically address in the Stage 4 integration PR (Stage 2.7 reviews are usually more structural and major). Feel free to make these editorial changes now if you like, but there's no need to worry about it.

**Comment by o-** [comment]
It looks like [test262 mostly didn't land](https://github.com/tc39/test262/pulls?q=is%3Apr+immutable-arraybuffer) yet. Leaving that as a note to prospective implementers.

V8 has a prototype by now. The implementation is not zero-copy. That will require some more thinking.

**Comment by styfle** [comment]
> V8 has a prototype by now.

@o- Thats great!

 Is there an issue tracker I can follow along? I'm curious when immutable arraybuffers will land in Node.js and Chromium.

**Comment by o-** [comment]
> Is there an issue tracker I can follow along? I'm curious when immutable arraybuffers will land in Node.js and Chromium.

There is, at https://issues.chromium.org/issues/450237486

**Comment by fabiospampinato** [comment]
> V8 has a prototype by now. The implementation is not zero-copy. That will require some more thinking.

Hopefully it will be zero-copy when it ships, otherwise I don't really see the point of it.

**Comment by o-** [comment]
Agreed. We need some time to think through the security implications, but I don't see a fundamental problem here. For now we're holding out for the conditional stage 3 to become unconditional stage 3 (i.e., test262 finalized) before prioritizing.

**Comment by o-** [comment]
Actually, as long as #55 remains not fixed the immutability does not actually hold and we have to copy.

**Comment by ljharb** [comment]
imo #55 must be fixed, in the way described.

**Comment by bakkot** [comment]
Fix for #55: https://github.com/tc39/proposal-immutable-arraybuffer/pull/62

**Comment by styfle** [comment]
I created a Web IDL PR here - https://github.com/whatwg/webidl/pull/1598
